# Site settings
title: "The Curcumin Cure"
name: "Tanya Mandyam"
description: "Learn about how curcumin aides with gut microbiome health improvement, circadian rhythm adjustment, reduction of anti-inflammatory markers, and more!"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site



# Build settings
markdown: kramdown
